language: java
jdk: oraclejdk7
env:
  global:
   - secure: "FPqieNWtuF/67ZPPDc6izeZZo8/bmxZv5dS5/Zcpx+m658afjH0REewD2DcITYc5j6lY/QC8kiM5g5Q4ApJRQKWShAEdl4uqr4q9CeFFpowdmnBTnX+Kn0DU2i+HmncxonAJ6gOGTxRLBMzaZtKuHjQ4hsLxbDftuN7fPvdnA4s="
   - secure: "Lvem0QpGUqumKXl+UAJQRt8qJHpaKdaktY2YwYgtglArkLwIQ7/N6V/0hlDbdkJxxqLWjo0W8V80UdiuXAurIn7WyBQplSioPFBBpkyNYh6rIlLGQg2b6gpap1LnUSrRbe2Y0fPn80AxKN3wL/yriJ/oB+I3uPAT7RW84LWULjA="
   - secure: "Jv59VEU3hkoj1ciVUdCZjwlbuAaK9f7oEEDqEr7OAd+w7zirW37rRH7Tj0PElYANv5S5r2N83x+uwePgvdisZTLNEhoIpipH2h4c0Roc4f5wfQ21AJO1cbaPcp4ZjPfZQ269/CU/NpoAKHToKSbUYGeIj+8EUW9mk36agVKn/UE="
  matrix:
    - ANDROID_SDKS=android-19,sysimg-19  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
branches:
  only:
    - master
before_install:
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
install:
  - true
before_script:
script:
after_success:

